This problem canbe solved by Topic Modeling.It allow us to efficiently analyze large amount of text by clustering documents into topic and large amount of text data is unlabelled. If we have unlabelled data then we can attempt to discover labels which means attempting to discover cluster of documents grouped together by topic.  

In [ ]:
import numpy as np
import pandas as pd
import spacy

In [87]:
df_human = pd.read_csv('C:/Users/ANKIT/Desktop/data_science_project-master/human.csv')

In [88]:
df_human.head()

Article
0                     Grease Monkey's current market
1  Schlumberger's management shift, asset restruc...
2  enough to ease the trade deficit's drag on the...
3  against a targeted 1.6 billion, official figur...
4                  Chancellor of the Exchequer Nigel

In [89]:
df_human['Article'][0]

"Grease Monkey's current market"

In [90]:
len(df_human)

85776

In [91]:
from sklearn.feature_extraction.text import CountVectorizer

In [92]:
cv = CountVectorizer(max_df = 0.9, min_df = 2, stop_words = 'english')

In [93]:
#It is a unsupervised learning need to fit on entire dataset.
dtm_human = cv.fit_transform(df_human['Article'])

In [94]:
# "Document * Words" we have 19591 terms(words) and 85776 articles has each line is "unique".
dtm_human

<85776x19591 sparse matrix of type '<class 'numpy.int64'>'
	with 809331 stored elements in Compressed Sparse Row format>

LDA is based on Probability Distribution
Assumptions of LDA for Topic Modeling
- Datatsets with similar topics use similar groups of words.
- Latent topics can then be founded by searching for groups of words that frequently occur in datasets across the corpus.
- Documents are probability distribution over latent topics.
- Topics themselves are probability distribution over words.

In [95]:
from sklearn.decomposition import LatentDirichletAllocation

In [117]:
#We can choose different number of n_components depending on our requiremnet and random words are assigned at the beginning.
LDA = LatentDirichletAllocation(n_components = 3, random_state = 42)

In [118]:
LDA.fit(dtm_human)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=3, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [ ]:
#Grabbing vocabulary of words

In [119]:
len(cv.get_feature_names())

19591

In [120]:
type(cv.get_feature_names())

list

In [121]:
cv.get_feature_names()[1]

'000'

In [122]:
#Random words generation
import random
random_word_id = random.randint(0, 19591)
cv.get_feature_names()[random_word_id]

'random'

In [ ]:
#Grabbing topics

In [123]:
len(LDA.components_)

3

In [124]:
type(LDA.components_)

numpy.ndarray

In [125]:
LDA.components_.shape

(3, 19591)

In [126]:
single_topic = LDA.components_[0]

In [127]:
single_topic.argsort()

array([ 6632,  2410, 11393, ..., 10982, 17954, 15651], dtype=int64)

In [128]:
#Argsort index position sorted from least to Graetest
#Top 20 values(20 Gratest values)
#Last 20 values of argsort
single_topic.argsort()[-20:] #Grabs the last 20 values of .argsort()

array([ 8445,  9496,  1717, 16882,  8047, 13933,  4595, 19209,  5706,
        9959, 17929,  5046,  4597, 11811, 12309, 12689,  2729, 10982,
       17954, 15651], dtype=int64)

In [129]:
top_twenty_words = single_topic.argsort()[-20:]
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

group
industry
agreement
statement
gas
president
companies
wheat
department
japan
told
corp
company
mln
new
oil
bank
lt
tonnes
said


In [ ]:
#Grabbing highest probability words per topic

In [130]:
for i, topic in enumerate(LDA.components_):
    print(f"The Top 20 words per topic #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-20:]])
    print('\n')
    print('\n')

The Top 20 words per topic #0
['group', 'industry', 'agreement', 'statement', 'gas', 'president', 'companies', 'wheat', 'department', 'japan', 'told', 'corp', 'company', 'mln', 'new', 'oil', 'bank', 'lt', 'tonnes', 'said']




The Top 20 words per topic #1
['growth', 'rates', 'rise', 'bank', 'week', 'price', 'exchange', 'january', 'dollar', 'february', '1986', '1987', 'rate', 'prices', 'company', 'market', 'trade', 'year', 'said', 'pct']




The Top 20 words per topic #2
['said', 'shares', 'corp', '1986', 'revs', 'year', 'stock', 'share', 'qtr', 'profit', 'shr', 'billion', 'loss', 'lt', 'net', 'cts', '000', 'dlrs', 'vs', 'mln']






In [140]:
df_human

Article  Topic
0                         Grease Monkey's current market      0
1      Schlumberger's management shift, asset restruc...      1
2      enough to ease the trade deficit's drag on the...      1
3      against a targeted 1.6 billion, official figur...      1
4                      Chancellor of the Exchequer Nigel      0
...                                                  ...    ...
85771                           Rev 86.4 mln vs 87.0 mln      2
85772  the following breakdown of grain remaining in ...      0
85773  determine the effects, if any, of the final re...      1
85774                The Bank of Japan intervened in the      0
85775  January 1985 from former chairman Marvin L. Wa...      0

[85776 rows x 2 columns]

In [134]:
topic_results = LDA.transform(dtm_human)

In [135]:
topic_results.shape

(85776, 3)

In [136]:
topic_results[0].round(2)

array([0.5 , 0.43, 0.07])

In [137]:
topic_results[0].argmax()

0

In [138]:
df_human['Topic'] = topic_results.argmax(axis=1)

In [139]:
#Topic gives which document corresponds to which article.
df_human

Article  Topic
0                         Grease Monkey's current market      0
1      Schlumberger's management shift, asset restruc...      1
2      enough to ease the trade deficit's drag on the...      1
3      against a targeted 1.6 billion, official figur...      1
4                      Chancellor of the Exchequer Nigel      0
...                                                  ...    ...
85771                           Rev 86.4 mln vs 87.0 mln      2
85772  the following breakdown of grain remaining in ...      0
85773  determine the effects, if any, of the final re...      1
85774                The Bank of Japan intervened in the      0
85775  January 1985 from former chairman Marvin L. Wa...      0

[85776 rows x 2 columns]