This problem canbe solved by Topic Modeling.It allow us to efficiently analyze large amount of text by clustering documents into topic and large amount of text data is unlabelled. If we have unlabelled data then we can attempt to discover labels which means attempting to discover cluster of documents grouped together by topic.  

In [1]:
import numpy as np
import pandas as pd
import spacy

In [2]:
df_machine = pd.read_csv('C:/Users/ANKIT/Desktop/data_science_project-master/machine.csv')

In [4]:
df_machine.head()

Article
0                         Np^g tj5vQ  key NKVZl31 ZV
1                 EcN !d7g moTL!3c* e^n qsG page l0u
2   @@rvbv 5r gYXWL police  nVV8 RZD.fV&2n Jc0 EQ2iX
3       pZ80yue ^  difference 8Z8Z i VhK,Tn Mqj!RpIy
4  bKQIM@v jd3D6nnK qlru9 administration c XhM%A6...

In [5]:
df_machine['Article'][0]

'Np^g tj5vQ  key NKVZl31 ZV'

In [6]:
len(df_machine)

500

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer(max_df = 0.9, min_df = 2, stop_words = 'english')

In [9]:
dtm_machine = cv.fit_transform(df_machine['Article'])

In [11]:
# "Document * Words" we have 253 terms(words) and 500 articles has each line is "unique".
dtm_machine

<500x253 sparse matrix of type '<class 'numpy.int64'>'
	with 562 stored elements in Compressed Sparse Row format>

LDA is based on Probability Distribution
Assumptions of LDA for Topic Modeling
- Datatsets with similar topics use similar groups of words.
- Latent topics can then be founded by searching for groups of words that frequently occur in datasets across the corpus.
- Documents are probability distribution over latent topics.
- Topics themselves are probability distribution over words.

In [12]:
from sklearn.decomposition import LatentDirichletAllocation

In [13]:
#We can choose different number of n_components depending on our requiremnet and random_state is used because words are assigned at the beginning.
LDA = LatentDirichletAllocation(n_components = 7, random_state = 42)

In [14]:
LDA.fit(dtm_machine)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [ ]:
#Grabbing vocabulary of words.

In [15]:
len(cv.get_feature_names())

253

In [16]:
type(cv.get_feature_names())

list

In [17]:
cv.get_feature_names()[1]

'0m'

In [42]:
#Random words generation
import random
random_word_id = random.randint(0, 253)
cv.get_feature_names()[random_word_id]
#cv.get_feature_names()[1]


'visit'

In [ ]:
#Grabbing topics

In [43]:
len(LDA.components_)

7

In [44]:
type(LDA.components_)

numpy.ndarray

In [22]:
LDA.components_.shape

(7, 253)

In [23]:
single_topic = LDA.components_[0]

In [24]:
single_topic.argsort()

array([223, 229, 102,  14,  65,  23, 176, 110, 221,  85, 174, 157,  88,
        31,  34,  79, 127,  21,  99,   2, 228,  16,  90, 109,  37,  46,
       141, 216, 238, 132,  86, 165, 128,  57, 245, 130, 112, 148, 144,
       217, 225,  52,  59,  28,  17, 104, 187,  80, 235, 113,   9, 214,
        64, 230, 121,  13, 243, 224, 146, 205, 173, 159,  32, 181, 234,
       210, 199,  18, 197, 131, 251, 158,  45,  89, 185,  98,  72,  12,
       232, 183,  20,  50, 161,  61,   7,  95,  35,  78, 163,  36,  96,
        24, 100,  22, 172,  15, 155,   1, 139,  54, 106, 236, 212,  81,
       117, 116, 134, 114, 166, 171, 179,  91, 180, 192,  43,  83, 206,
       135, 136, 137, 122,  66,  47, 150,  58,   3,  87, 101, 147,  71,
       182, 215, 248, 154, 213,  62,  38, 186, 178, 125,  68,  19, 209,
       133, 115,  44, 204, 239, 233,   8, 202, 246,  10, 219,  84,  70,
       151, 240, 218, 190, 126,  97, 149, 119,  77, 168,  55, 203, 105,
       200,  82, 211, 142, 191,  30, 247,   6, 170, 111,  63,  4

In [25]:
#Argsort index position sorted from least to Graetest
#Top 20 values(20 Gratest values)
#Last 20 values of argsort
single_topic.argsort()[-20:]

array([227, 145, 129, 249, 124, 196, 231,  40,  94,  74], dtype=int64)

In [27]:
top_twenty_words = single_topic.argsort()[-20:]
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

society
zt
nk
quickly
b1
jg
i1
mk
specific
jr
weight
mp
kn
ze
jy
sr
wo
cb
gk
ew


In [ ]:
#Grabbing highest probability words per topic

In [28]:
for i, topic in enumerate(LDA.components_):
    print(f"The Top 20 words per topic #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-20:]])
    print('\n')
    print('\n')

The Top 15 words per topic #0
['jg', 'i1', 'mk', 'specific', 'jr', 'weight', 'mp', 'kn', 'ze', 'jy', 'sr', 'wo', 'cb', 'gk', 'ew']




The Top 15 words per topic #1
['bt', 'glass', 'participant', 'cn', 'age', 'lb', 'xqi', 'aj', 'hm', 'expect', 'cj', 'k9', 'certain', 'vq', 'xy']




The Top 15 words per topic #2
['tr', 'mr', '4i', 'dh', 'uq', 'industry', 'wz', 'g4', 'aa', 'pass', 'jd', 'kx', 'watch', 'pc', 'hour']




The Top 15 words per topic #3
['gs', 'aq', 'past', 'h0', 'ri', 'wf', '14', 'hf', 'vm', 'zb', 't6', 'ap', 'book', 'college', 'il']




The Top 15 words per topic #4
['rb', 'bo', 'public', 'ju', 'q8', 'ft', 'ik', 'ml', 'clear', 'ph', 'jn', 'central', 'mu', 'office', 'cs']




The Top 15 words per topic #5
['fw', 'hk', 'community', 'ak', 'et', 'fz', 'cf', 'peace', 'visit', 'ig', '90', 'eb', 'cl', 'xx', 'size']




The Top 15 words per topic #6
['success', 'fv', 'uv', 'fe', 'br', 'bm', 'kd', 'fyp', 'wg', 'lt', 'd0', 'value', 'aw', '6w', 'yq']






In [29]:
df_machine

Article
0                           Np^g tj5vQ  key NKVZl31 ZV
1                   EcN !d7g moTL!3c* e^n qsG page l0u
2     @@rvbv 5r gYXWL police  nVV8 RZD.fV&2n Jc0 EQ2iX
3         pZ80yue ^  difference 8Z8Z i VhK,Tn Mqj!RpIy
4    bKQIM@v jd3D6nnK qlru9 administration c XhM%A6...
..                                                 ...
495                                 D popular %dL84N3w
496                        #$hAlw4 jN s0P#V% manager w
497                            2D color &Ww l, !VA*!Cy
498                                        wO!& time y
499  9rE Q private tQ5A, 0TH*nhK *Ze#zPcf x42L@VfE ...

[500 rows x 1 columns]

In [33]:
topic_results = LDA.transform(dtm_machine)

In [32]:
topic_results.shape

(500, 7)

In [34]:
topic_results[0].round(2)

array([0.07, 0.07, 0.07, 0.57, 0.07, 0.07, 0.07])

In [35]:
topic_results[0].argmax()

3

In [37]:
df_machine['Topic'] = topic_results.argmax(axis=1)

In [38]:
#Topic gives which document corresponds to which article.
df_machine

Article  Topic
0                           Np^g tj5vQ  key NKVZl31 ZV      3
1                   EcN !d7g moTL!3c* e^n qsG page l0u      0
2     @@rvbv 5r gYXWL police  nVV8 RZD.fV&2n Jc0 EQ2iX      6
3         pZ80yue ^  difference 8Z8Z i VhK,Tn Mqj!RpIy      0
4    bKQIM@v jd3D6nnK qlru9 administration c XhM%A6...      0
..                                                 ...    ...
495                                 D popular %dL84N3w      0
496                        #$hAlw4 jN s0P#V% manager w      4
497                            2D color &Ww l, !VA*!Cy      4
498                                        wO!& time y      0
499  9rE Q private tQ5A, 0TH*nhK *Ze#zPcf x42L@VfE ...      0

[500 rows x 2 columns]